replicaCount: 1

image:
  repository: us-east1-docker.pkg.dev/dogfood-cx/registryrepository/arca-agent
  tag: latest
  pullPolicy: Always

serviceAccount:
  name: arca-agent

rbac:
  create: true

resources: {}

logLevel: INFO  # Default log level