apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentconfigs.operator.arca.io
  annotations:
    "helm.sh/hook": pre-install
spec:
  group: operator.arca.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                discoveryLabel:
                  type: string
                tetrate:
                  type: object
                  properties:
                    endpoint:
                      type: string
                    apiToken:
                      type: string
                    username:
                      type: string
                    password:
                      type: string
                    organization:
                      type: string
                    tenant:
                      type: string
  scope: Namespaced
  names:
    plural: agentconfigs
    singular: agentconfig
    kind: AgentConfig
    shortNames:
      - acfg