# managerconfig_crd.yaml

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managerconfigs.operator.arca.io
spec:
  group: operator.arca.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                managerSetting:
                  type: string
  scope: Namespaced
  names:
    plural: managerconfigs
    singular: managerconfig
    kind: ManagerConfig
    shortNames:
      - mcfg
