apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arca-manager.fullname" . }}
  labels:
    {{- include "arca-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arca-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arca-manager.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: arca-manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.logLevel }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
