# agentconfig_crd.yaml

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentconfigs.operator.arca.io
spec:
  group: operator.arca.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                agentSetting:
                  type: string
  scope: Namespaced
  names:
    plural: agentconfigs
    singular: agentconfig
    kind: AgentConfig
    shortNames:
      - acfg
