# Taskfile.yaml
version: '3'

vars:
  REGISTRY: us-east1-docker.pkg.dev/dogfood-cx/registryrepository
  IMAGE_NAME: arca-agent
  TAG: latest

tasks:
  build-image:
    desc: Build Docker image for the Arca-Agent
    cmds:
      - | 
        docker build --platform linux/amd64 \
          -t {{.REGISTRY}}/arca-agent:latest . 
      - docker tag {{.REGISTRY}}/arca-agent:latest {{.REGISTRY}}/arca-agent:{{.TAG}}
    silent: false

  push-image:
    desc: Push the Docker image to the registry
    cmds:
      - gcloud auth configure-docker {{.REGISTRY}} --quiet
      - docker push {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.TAG}}
    silent: false

  helm-upgrade:
    desc: Upgrade the Helm release for the Arca-Agent
    cmds:
      - helm upgrade arca-agent ./helm -n arca-system --create-namespace
    silent: false

  k8s-restart:
    desc: Restart the Kubernetes deployment
    cmds:
      - kubectl rollout restart deployment/arca-agent -n arca-system
    silent: false

  release-now:
    desc: Perform a full release cycle of the Arca-Agent
    cmds:
      - task: build-image
      - task: push-image
      - task: helm-upgrade
      - task: k8s-restart